python_project/djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include

# from pages import views as page_views #NEW
from django.conf import settings # NEW
from django.conf.urls.static import static # NEW


urlpatterns = [
    
    path('agronomy/', include('agronomy.urls')),
    path('', include('pages.urls')),
    
    # Urls for account management
    path('accounts/', include('accounts.urls')), # NEW
    # NEW: path for account management
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('admin/', admin.site.urls),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
     + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_project/djangoproject/pages/urls.py
from pages import views as page_views #NEW
from django.contrib import admin
from django.urls import path

app_name = 'pages'

urlpatterns = [
    
    path('', page_views.home, name='home'), #NEW
    path('Trends/', page_views.Trends,name='Trends'),
    path('best_pratices/', page_views.practices,name='practices'),
    path('new_technologies/',page_views.technologies,name='technologies'),
    path('about/',page_views.about,name='about'),
    path('key_events/',page_views.events,name='events'),

    
]  

python_project/djangoproject/base/models.py
from django.db import models

# Create your models here.

python_project/djangoproject/base/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'blog/home.html')

def home(request):
    return render(request, 'pages/home.html')

def Trends(request):
    return render(request, 'pages/Trends.html')

def practices(request):
    return render(request, 'pages/best_pratices.html')

python_project/djangoproject/base/templates/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agricultural Information Platform</title>
    <link rel="stylesheet" href="/static/css/base.css" type="text/css">
</head>
<body>
    <nav>
        <ul>
            <li><a href="/">Accueil</a></li>
            <li><a href="{% url 'pages:Trends' %}">Agricultural Trends</a></li>
            <li><a href="{% url 'pages:practices' %}">Best practices</a></li>
            <li><a href="{% url 'pages:technologies' %}">New technologies</a></li>
            <li><a href="{% url 'pages:events' %}">Key events</a></li>
            <li><a href="{% url 'pages:about' %}">About us</a></li>
            <li><a href="/agronomy/">Voir nos produits agricoles</a></li>
        </ul>
    </nav>
{% block 'content' %}
{% endblock %}
</body>
</html>