python_project/djangoproject/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.user_profile, name='profile'),
    path('create/', views.create_account, name='create'),
    path('profile/change/', views.change_profile, name='change-profile'),
]

python_project/djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include

# from pages import views as page_views #NEW
from django.conf import settings # NEW
from django.conf.urls.static import static # NEW


urlpatterns = [
    
    path('agronomy/', include('agronomy.urls')),
    path('', include('pages.urls')),
    
    # Urls for account management
    path('accounts/', include('accounts.urls')), # NEW
    # NEW: path for account management
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('admin/', admin.site.urls),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
     + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_project/djangoproject/pages/urls.py
from pages import views as page_views #NEW
from django.contrib import admin
from django.urls import path

app_name = 'pages'

urlpatterns = [
    
    path('', page_views.home, name='home'), #NEW
    path('Trends/', page_views.Trends,name='Trends'),
    path('best_pratices/', page_views.practices,name='practices'),
    path('new_technologies/',page_views.technologies,name='technologies'),
    path('about/',page_views.about,name='about'),
    path('key_events/',page_views.events,name='events'),

    
]  

python_project/djangoproject/pages/templates/pages/Trends.html
{% extends 'base_template.html' %}
{% load static %}
{% block 'content' %}
    <header>
        <h1>Agricultural Trends</h1>
    </header>

    <div>
        <img src="{% static 'pages/img/tends.jpg' %}">
        <img src="{% static 'pages/img/trends.jpg' %}">
    </div>

    <main>
        <p>Explore the latest agricultural trends here.</p>
        
        <h2>Dernières tendances agricoles</h2>
        
        <p>Les tendances agricoles actuelles mettent en avant l'importance croissante de l'agriculture numérique. Les technologies telles que l'Internet des objets (IoT), l'intelligence artificielle (IA) et la blockchain transforment la manière dont les agriculteurs gèrent leurs exploitations et prennent des décisions.</p>
        
        <p>L'agriculture de précision continue de se développer, offrant aux agriculteurs des outils sophistiqués pour surveiller et optimiser la santé des cultures, réduire les intrants et améliorer les rendements de manière durable.</p>
        
        <p>La durabilité est au cœur des tendances actuelles, avec une attention particulière portée à la régénération des sols, à la réduction de l'empreinte carbone et à la préservation de la biodiversité pour assurer la pérennité des systèmes agricoles.</p>
        
        <p>Les modèles d'agriculture circulaire gagnent en popularité, promouvant une approche holistique de la production alimentaire qui vise à réduire les déchets, à valoriser les sous-produits et à créer des boucles de production plus durables.</p>
        
        <p>La diversification des cultures et des systèmes agricoles est également une tendance notable, avec une plus grande adoption de cultures alternatives, de mélanges de cultures et d'agroforesterie pour améliorer la résilience des exploitations et favoriser une utilisation plus efficace des terres.</p>
        
        <p>Enfin, l'accent mis sur la transparence et la traçabilité alimentaire est de plus en plus marqué, les consommateurs cherchant des informations sur l'origine des produits, les pratiques agricoles utilisées et leur impact environnemental pour prendre des décisions d'achat éclairées.</p>
        
    </main>
    <footer>
        <p>&copy; 2024-2023 Agricultural Information Platform</p>
    </footer>
    {% endblock %}

python_project/djangoproject/pages/templates/pages/about.html
{% extends 'base_template.html' %}
{% load static %}
{% block 'content' %}

    
    <header>
        <h1>À Propos de Notre Plateforme d'Informations Agricoles</h1>
    </header>

    <section>
        <h3>Qui Sommes-Nous?</h3>
        <p>Nous sommes une plateforme dédiée à fournir des informations agricoles de qualité, des actualités sur les dernières technologies et pratiques agricoles, ainsi que des conseils pour les agriculteurs et les professionnels du secteur agricole.</p>
    </section>

    <section>
        <h3>Notre Mission</h3>
        <p>Notre mission est de promouvoir l'innovation et la durabilité dans le domaine agricole en partageant des connaissances précieuses et en encourageant l'adoption de pratiques agricoles modernes et respectueuses de l'environnement.</p>
    </section>

    <section>
        <h3>Contactez-Nous</h3>
        <p>Pour toute question, suggestion ou demande d'information supplémentaire, n'hésitez pas à nous contacter à l'adresse email contact@plateformedinformationsagricoles.com
            Ou soit sur benedictemak2@gmail.com</p>
    </section>
        
 
    <!-- <footer>
        <p>&copy; 2024 Agricultural Information Platform</p>
    </footer> -->

{% endblock %}        

python_project/djangoproject/pages/templates/pages/best_pratices.html
{% extends 'base_template.html' %}
{% load static %}
{% block 'content' %}
</head>
<body>
    
    <header>
        <h1>Best Practices in Agriculture</h1>
    </header>
    <main>
        <p>Discover the best practices to enhance agricultural productivity.</p>
    </main>

    <div>
        <img src="{% static 'pages/img/pratices.jpg' %}">
    </div>
    <ul>
        <li><strong>Agriculture de conservation :</strong> Cette approche vise à réduire au minimum le travail du sol, à maintenir une couverture végétale permanente et à diversifier les cultures pour améliorer la santé des sols et réduire l'érosion.</li>
        <li><strong>Agriculture de précision :</strong> L'utilisation de technologies telles que les drones, les capteurs et les systèmes d'information géographique pour optimiser les pratiques agricoles, améliorer l'efficacité des intrants et maximiser les rendements..</li>
        <li><strong>Agroforesterie :</strong>  L'intégration d'arbres dans les exploitations agricoles pour améliorer la biodiversité, la santé des sols, la régulation climatique et offrir des revenus supplémentaires grâce à la production de bois, de fruits ou d'autres produits forestiers.</li>
        <li><strong>Agriculture biologique :</strong>  La culture d'aliments sans l'utilisation de produits chimiques synthétiques, en favorisant des méthodes plus naturelles pour fertiliser et protéger les cultures, tout en préservant la santé des sols et de l'environnement.</li>
        <li><strong>Utilisation durable de l'eau:</strong> Des pratiques telles que l'irrigation de précision, la collecte des eaux de pluie, et la gestion efficace de l'eau pour garantir une utilisation responsable et durable des ressources en eau.</li>
        <li><strong>Rotation des cultures et cultures associées:</strong>Alterner les cultures et combiner différentes espèces végétales pour améliorer la fertilité du sol, réduire les maladies et ravageurs, et favoriser une utilisation efficace des ressources.</li>
        <li><strong>Utilisation de semences adaptées au climat:</strong>Le choix de variétés de cultures adaptées aux conditions climatiques locales pour garantir des rendements plus stables et résilients face aux changements climatiques.</li>
    </ul>
    
    <p>
        En adoptant ces pratiques agricoles modernes et durables, les agriculteurs peuvent améliorer la productivité, réduire leur impact environnemental et contribuer à la création d'un système agricole plus résilient et respectueux de l'environnement.
    </p>
    <footer>
        <p>&copy; 2024 Agricultural Information Platform</p>
    </footer>

{% endblock %}

python_project/djangoproject/pages/templates/pages/home.html
{% extends 'base_template.html' %}
{% load static %}
{% block 'content' %}

    <header>
       
        <h1>Bienvenue sur Agricultural Information Platform</h1>
        <p>Obtenez les dernières informations sur les tendances agricoles, les meilleures pratiques,
        les nouvelles technologies, les réglementations et les événements clés dans le domaine de l'agronomie.</p>
    </header>

    <main>
        <p>
            <em>{% if user.is_authenticated %}{{ user.username }}{% endif %}</em>
        </p>
    
        {% if user.is_authenticated %}
            <a class="btn" href="{% url 'accounts:profile' %}">View Profile</a>
        {% else %}
        <a href="{% url 'login' %}">
            <button>Login</button>
        </a>    
        {% endif %}
    </main>
        

    <article>
    <div>
        <img src="{% static 'pages/img/images (12).jpg' %}">
        <img src="{% static 'pages/img/images (14).jpg' %}">
        <img src="{% static 'pages/img/images (8).jpg' %}">
    </div>
    </article> 
    
    {% endblock %}

python_project/djangoproject/pages/templates/pages/key_events.html
{% extends 'base_template.html' %}
{% load static %}
{% block 'content' %}

    <header>
        <h1>Événements Clés en Agriculture pour 2024</h1>
    </header>
        <h3>Les Événements Majeurs de l'Année</h3>
        <p>Découvrez les dernières actualités sur les événements clés qui façonnent le secteur agricole en 2024, des conférences aux salons professionnels en passant par les avancées technologiques révolutionnaires.</p>
    
        <h3>Calendrier des Événements</h3>
        <p>Consultez notre calendrier interactif pour ne manquer aucun événement important de l'année 2024, des symposiums aux formations spécialisées en agriculture.</p>
    
        <h3>Dernières Actualités</h3>
        <p>Restez informé des dernières tendances et développements dans le domaine agricole en explorant nos articles sur les événements clés qui impactent le secteur agricole en 2024.</p>
    
    <footer>
        <p>&copy; 2024 Agricultural Information Platform</p>
    </footer>

{% endblock %}    

python_project/djangoproject/pages/templates/pages/new_technologies.html
{% extends 'base_template.html' %}
{% load static %}
{% block 'content' %}

    
    <header>
        <h1>New Technologies in Agriculture</h1>
    </header>

    <h2>Les Dernières Avancées Technologiques en Agriculture pour 2024</h2>

    <p>Découvrez les toutes dernières technologies révolutionnant le secteur agricole en 2024, de l'agriculture de précision à l'intelligence artificielle.</p>

    <h3>Nos Services</h3>
    
    <ul>
        <li>Agriculture de Précision </li>
        <li>Robotique Agricole</li>
        <li>IoT (Internet des Objets) en Agriculture</li>
        <li>Technologies Vertes pour une Agriculture Durable</li>
        <img src="{% static 'pages/img/images (5).jpg' %}">
        <img src="{% static 'pages/img/images.jpg' %}">
    </ul>

    <p>Nous nous engageons à vous fournir les toutes dernières informations sur les technologies agricoles de pointe pour accroître l'efficacité et la durabilité de l'agriculture.</p>


    <footer>
        <p>&copy; 2024 Agricultural Information Platform</p>
    </footer>

{% endblock %}    