python_project/djangoproject/agronomy/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'agronomy'
urlpatterns = [
    path('', views.home, name='home'),
    path('produit/<int:produit_id>/', views.produit_view, name='produit_view'),
    path('produit/<int:produit_id>/', views.produit_detail, name='produit_detail'),
    path('produit/add/', views.produit_add,name='produit_add'),
    path('produit/<int:produit_id>/change/', views.produit_change, name='produit_change'),
    path('produit/<int:produit_id>/delete/', views.produit_delete, name='produit_delete'),
    path('produit/<int:produit_id>/publish/', views.produit_publish, name='produit_publish'),


    path('articles/', views.article_list, name='article_list'),
    path('articles/add/', views.article_add, name='article_add'),
    path('articles/<int:pk>/', views.article_detail, name='article_detail'),
    path('articles/<int:pk>/edit/', views.article_change, name='article_change'),
    path('articles/<int:pk>/delete/', views.article_delete, name='article_delete'),


    path('vote/article/<int:article_id>/', views.vote, name='vote_article'),
    path('vote/event/<int:event_id>/', views.vote, name='vote_event'),
    path('event/<int:event_id>/', views.event_view, name='view_event'),

    path('upload-article/', views.upload_article, name='upload_article'),
    path('upload-event/', views.upload_event, name='upload_event'),


    path('events/', views.event_list, name='event_list'),
    path('events/<int:pk>/', views.event_detail, name='event_detail'),
    path('events/new/', views.create_event, name='create_event'),
    path('events/<int:pk>/update/', views.update_event, name='update_event'),
    path('events/<int:pk>/delete/', views.delete_event, name='delete_event'),


]

python_project/djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include

# from pages import views as page_views #NEW
from django.conf import settings # NEW
from django.conf.urls.static import static # NEW


urlpatterns = [
    
    path('agronomy/', include('agronomy.urls')),
    path('', include('pages.urls')),
    
    # Urls for account management
    path('accounts/', include('accounts.urls')), # NEW
    # NEW: path for account management
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('admin/', admin.site.urls),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
     + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_project/djangoproject/pages/urls.py
from pages import views as page_views #NEW
from django.contrib import admin
from django.urls import path

app_name = 'pages'

urlpatterns = [
    
    path('', page_views.home, name='home'), #NEW
    path('Trends/', page_views.Trends,name='Trends'),
    path('best_pratices/', page_views.practices,name='practices'),
    path('new_technologies/',page_views.technologies,name='technologies'),
    path('about/',page_views.about,name='about'),
    path('key_events/',page_views.events,name='events'),

    
]  

python_project/djangoproject/agronomy/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from datetime import date


# Create your models here.

# class Person(models.Model):
#     first_name = models.CharField(max_length=30)
#     last_name = models.CharField(max_length=30)


User = settings.AUTH_USER_MODEL


class Produits(models.Model):
    class Meta:
        permissions = [
            ("publish_product", "Can publish a Product")
        ]

    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(unique=True, max_length=255)
    image = models.ImageField(upload_to="produit_images", null=True, blank=True)
    title = models.CharField(max_length=100)
    content = models.TextField(blank=True)
    is_published = models.BooleanField(default=False)
    pub_date = models.DateField(null=True, blank=True)
    

    def __str__(self):
        return self.title + ("*" if self.is_published else "") 

    def get_absolute_url(self):
        return "/agronomy/produit/" + str(self.id) + "/"

  
class Event(models.Model):
    title = models.CharField(max_length=255, default='Untitled Event')
    description = models.TextField(default='')
    start_date = models.DateField(default=date.today)
    end_date = models.DateField(default=date(2024, 12, 31))
    location = models.CharField(max_length=255, default='TBD')
    organizer = models.CharField(max_length=255, default='Unknown Organizer')
    contact_email = models.EmailField(default='default@example.com')
    website = models.URLField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    
    def get_vote_count(self):
        return self.vote_set.count()

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=100, default='Titre de l\'article')
    introduction = models.TextField(default='Introduction à l\'article...')
    technical_info = models.TextField(default='Informations techniques sur les techniques agricoles...')
    practical_tips = models.TextField(default='Conseils pratiques et recommandations pour les agriculteurs...')
    testimonials = models.TextField(default='Témoignages d\'agriculteurs ou d\'experts du secteur...')
    infographic = models.ImageField(upload_to='infographics/', default='images/default.png')
    links = models.URLField(default='http://www.example.com')
    conclusion = models.TextField(default='Conclusion de l\'article...')
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # Champ pour lier l'auteur de l'article

    def get_vote_count(self):
        return self.vote_set.count()
    def __str__(self):
        return self.title

class Agronome(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(blank=True)
    specialisation = models.TextField(blank=True)
    def __str__(self):
        return self.name 

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)  
    content = models.CharField(max_length=(500))
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

python_project/djangoproject/agronomy/forms.py
from django import forms
from .models import Produits
from .models import Article,Event

 
class ProduitForm(forms.ModelForm):
    class Meta:
        model = Produits
        fields = [ 'title', 'content','image', 'is_published','pub_date','author' ]


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','introduction','technical_info','practical_tips','testimonials','infographic','author','links','conclusion']

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = '__all__'

python_project/djangoproject/agronomy/views.py
from django.shortcuts import render, redirect, get_object_or_404
from datetime import datetime
from agronomy.models import*
from .forms import ProduitForm, ArticleForm
from .models import Article
from django.contrib.auth.decorators import permission_required, login_required
from .models import Event
from .forms import EventForm
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib import messages
from django.http import HttpResponse

from .models import Vote

def vote(request, article_id=None, event_id=None):
    if request.method == 'POST':
        if article_id:
            existing_vote = Vote.objects.filter(user=request.user, article__isnull=False).exists()
            if not existing_vote:
                Vote.objects.create(user=request.user, article_id=article_id)
                messages.success(request, 'Votre vote pour l\'article a été enregistré avec succès!')
            else:
                messages.error(request, 'Vous avez déjà voté pour un article!')
            return redirect('agronomy:article_list')
        elif event_id:
            existing_vote = Vote.objects.filter(user=request.user, event__isnull=False).exists()
            if not existing_vote:
                Vote.objects.create(user=request.user, event_id=event_id)
                messages.success(request, 'Votre vote pour l\'événement a été enregistré avec succès!')
            else:
                messages.error(request, 'Vous avez déjà voté pour un événement!')
            return redirect('agronomy:event_list')
    return redirect('agronomy:home')

@receiver(post_save, sender=Article)
@receiver(post_save, sender=Event)


def create_notification(sender, instance, created, **kwargs):
    if created:
        request = kwargs.get('request')
        if request:
            messages.info(request, f'New {sender.__name__} created: {instance.title}')
    return HttpResponse("Notification created successfully")

def home(request):
    produits = (Produits.objects
                .filter(is_published=True)
                .order_by('-pub_date')[:10])
    
    data = {
        'produits': produits,
        
        
    }
    
    return render(request, 'agronomy/home.html', data)


def produit_view(request, produit_id):
    produit = Produits.objects.get(id=produit_id)
    data = {
    'produit': produit
    }
    return render(request, 'agronomy/produit_view.html', data)


def produit_detail(request, produit_id):
    produit = get_object_or_404(Produits, id=produit_id)
    data = {
        'produit': produit
    }
    return render(request, 'agronomy/produit_detail.html', data)


@login_required
@permission_required('agronomy:add_produit', raise_exception=True)
def produit_add(request):
    if request.method == "POST":
        form = ProduitForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author = request.user
            blog_post = form.save()
            return redirect(blog_post)    # redirects to blog_post.get_absolute_url()
    else:
        form = ProduitForm()
    return render(request, 'agronomy/produit_add.html', { 'form': form })

@permission_required('agronomy.change_produit', raise_exception=True)
def produit_change(request, produit_id):
    produit = get_object_or_404(Produits, id=produit_id) # Need to fetch the specific object
    if request.method == "POST":
        form = ProduitForm(request.POST, request.FILES, instance=produit)
        if form.is_valid():
            produit = form.save() # This will update the object
            return redirect('/agronomy/')
    else:
        form = ProduitForm(instance=produit)
    return render(request, 'agronomy/produit_change.html', { 'form': form, 'produit': produit })

@permission_required('agronomy.delete_produit', raise_exception=True)
def produit_delete(request, produit_id):
    produit= get_object_or_404(Produits, id=produit_id)
    if request.method == "POST":
        produit.delete()
        return redirect('/agronomy/')
    return render(request, 'agronomy/produit_delete.html', { 'produit': produit })


def produit_publish(request, produit_id):
    produit = get_object_or_404(Produits, id=produit_id)
    if request.method == "POST":
        produit.is_published = True
        produit.pub_date = datetime.now()
        produit.save()
# Redirect to the post's detail page
    return redirect(produit)


def event_list(request):
    events = Event.objects.all()
    return render(request, 'agronomy/event_list.html', {'events': events})

def event_view(request, event_id):
    event = Event.objects.get(id=event_id)
    data = {
        'event': event
    }
    return render(request, 'agronomy/event_view.html', data)


def event_detail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES, instance=event)
        if form.is_valid():
            event=form.save()
    else:
        form = EventForm(instance=event)
    
    return render(request, 'agronomy/event_detail.html', {'event': event, 'event_form': form})

def create_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('agronomy:event_list')
    else:
        form = EventForm()
    return render(request, 'agronomy/event_form.html', {'form': form})

def update_event(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            event=form.save()
            return redirect('agronomy:event_detail', pk=pk)
    else:
        form = EventForm(instance=event)
    return render(request, 'agronomy/event_change.html', {'form': form, 'event':event})

def delete_event(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.method == 'POST':
        event.delete()
        return redirect('agronomy:event_list')
    return render(request, 'agronomy/event_confirm_delete.html', {'event': event})


def article_list(request):
    articles = Article.objects.all()
    return render(request, 'agronomy/article_list.html', {'articles': articles})

def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    data = {
        'article': article
        
    }
    
    return render(request, 'agronomy/article_detail.html',data)

@login_required
def article_add(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()  # Ne pas sauvegarder l'instance pour le moment
            article.author = request.user  # Associer l'auteur actuel
            article.save()  # Maintenant, sauvegarder l'instance avec l'auteur

            messages.success(request, 'Article added successfully')  # Ajout d'un message de succès
            return redirect('agronomy:article_list')

    else:
        form = ArticleForm()
    
    return render(request, 'agronomy/article_form.html', {'form': form})

def article_change(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            article=form.save()
            return redirect('agronomy:article_detail', pk=pk)
    else:
        form = ArticleForm(instance=article)
    return render(request, 'agronomy/article_change.html', {'form': form, 'article':article})

def article_delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('agronomy:article_list')
    return render(request, 'agronomy/article_delete.html', {'article': article})


def upload_article(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('agronomy:article_list')
    else:
        form = ArticleForm()
    return render(request, 'agronomy/upload_article.html', {'form': form})

def upload_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('agronomy:event_list')
    else:
        form = EventForm()
    return render(request, 'agronomy/upload_event.html', {'form': form})

python_project/djangoproject/agronomy/templates/agronomy/article_delete.html
{% extends 'base_template.html' %}

{% block 'title' %}{{ article.title }}{% endblock %}

{% block 'content' %}

    <h1>Confirmer la suppression de l'article "{{ article.title }}"</h1>
    <p>Êtes-vous sûr de vouloir supprimer cet article ?</p>
    <form action="{% url 'agronomy:article_delete' article.pk %}" method="post">
        {% csrf_token %}
        <button type="submit">Confirmer la suppression</button>
    </form>

{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/article_detail.html
{% block title %}
    
{% endblock %}

{% block content %}
    <p>
        <a href="{% url 'agronomy:article_list' %}">Articles_list</a>
    </p>

    {% if user.is_authenticated and user.is_staff %}
        <a href="{% url 'agronomy:article_change' article.pk %}">Modifier</a>
        <a href="{% url 'agronomy:article_delete' article.pk %}">Supprimer</a>
    {% endif %}
    
    <h1>{{ article.title }}</h1>
    <p><strong>Introduction:</strong> {{ article.introduction }}</p>
    <p><strong>Informations techniques:</strong> {{ article.technical_info }}</p>
    <p><strong>Conseils pratiques:</strong> {{ article.practical_tips }}</p>
    <p><strong>Témoignages:</strong> {{ article.testimonials }}</p>
    <p><strong>Auteur : </strong>{{ article.author }}</p>
    {% if article.infographic %}
        <img src="{{ article.infographic.url }}" alt="Infographic" style="width:400px">
    {% endif %}
    <p><strong>Liens:</strong> <a href="{{ article.links }}">{{ article.links }}</a></p>
    <p><strong>Conclusion:</strong> {{ article.conclusion }}</p>
    <p><strong>Nombre de votes:</strong> {{ article.get_vote_count }}</p>

    <!-- Boutons de partage vers les plateformes de médias sociaux -->
    <div class="social-share">
        <a href="https://twitter.com/intent/tweet?url={{ article.get_absolute_url }}" target="_blank">Partager sur Twitter</a>
        <a href="https://www.facebook.com/sharer/sharer.php?u={{ article.get_absolute_url }}" target="_blank">Partager sur Facebook</a>
    </div>

   
    <form method="post" action="{% url 'agronomy:vote_article' article.pk %}">
        {% csrf_token %}
        <button type="submit">Vote</button>
    </form>

    <form action="{% url 'agronomy:upload_article' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Télécharger l'article</button>
    </form>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #48c422;
            text-align: center;
            align-items: normal;
        }
        button, input[type="button"], input[type="submit"] {
            background-color: #2a6105;
            color: white;
            border: none;
            padding: 5px 10px;
            text-decoration: none;
            display: inline-block;
            font-size: 10px;
            margin: 2px 2px;
            cursor: pointer;
            border-radius: 5px;
        }

    </style>
{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/article_form.html
<p>
    <a href="{% url 'agronomy:article_list' %}">Articles_list</a>
</p>

{% block title %}Create a new Article{% endblock %}

{% block content %}

<form action="{% url 'agronomy:article_add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    
    <input type="submit" value="Submit">
</form>

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #48c422;
        text-align: center;
        align-items: normal;
    }
    button, input[type="button"], input[type="submit"] {
        background-color: #2a6105;
        color: white;
        border: none;
        padding: 5px 10px;
        text-decoration: none;
        display: inline-block;
        font-size: 10px;
        margin: 2px 2px;
        cursor: pointer;
        border-radius: 5px;
    }

</style>

{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/article_list.html
{% extends 'base_template.html' %}

{% block 'title' %}{% endblock %}

{% block 'content' %}

    <h1>Liste des Articles</h1>

    <a href="{% url 'agronomy:article_add' %}"><button>Add a New Article </button></a>
    
    <ul>
        {% for article in articles %}
            <li><a href="{% url 'agronomy:article_detail' article.pk %}">{{ article.title }}</a></li>
       
            <li><a href="{{ article.get_absolute_url }}"></a></li>
    
        {% endfor %}
    </ul>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <td>{{ article.author }}</td>
    
{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/article_view.html
{% extends 'base_template.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}

    <h1>{{ article.title }}</h1>
    
    <p><strong>Introduction:</strong> {{ article.introduction }}</p>
    
    <p><strong>Technical Information:</strong> {{ article.technical_info }}</p>
    
    <p><strong>Practical Tips:</strong> {{ article.practical_tips }}</p>
    
    <p><strong>Testimonials:</strong> {{ article.testimonials }}</p>
    
    {% if article.infographic %}
        <img src="{{ article.infographic.url }}" alt="Infographic">
    {% endif %}
    
    <p><strong>Links:</strong> <a href="{{ article.links }}">{{ article.links }}</a></p>
    
    <p><strong>Conclusion:</strong> {{ article.conclusion }}</p>
    

{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/event_confirm_delete.html
{% extends 'base_template.html' %}
{% block 'title' %}{% endblock %}

{% block 'content' %}

    <h1>Supprimer l'événement "{{ event.title }}"</h1>
    <p>Êtes-vous sûr de vouloir supprimer cet événement?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Supprimer</button>
    </form>
{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/event_detail.html
{% block title %} 

{% endblock %}

{% block content %}
    <p>
        <a href="{% url 'agronomy:event_list' %}">Events_list</a>
    </p>
    <h1>{{ event.title }}</h1>
    <p><strong>Description:</strong> {{ event.description }}</p>
    <p><strong>Date de début:</strong> {{ event.start_date }}</p>
    <p><strong>Date de fin:</strong> {{ event.end_date }}</p>
    <p><strong>Lieu:</strong> {{ event.location }}</p>
    <p><strong>Organisateur:</strong> {{ event.organizer }}</p>
    <p><strong>Nombre de votes:</strong> {{ event.get_vote_count }}</p>
    <p><strong>Contact:</strong> <a href="mailto:{{ event.contact_email }}">{{ event.contact_email }}</a></p>
    {% if event.website %}
        <p><strong>Site web:</strong> <a href="{{ event.website }}">{{ event.website }}</a></p>
    {% endif %}

    {% if user.is_authenticated and user.is_staff %}
        
        <a href="{% url 'agronomy:update_event' event.pk %}">Modifier</a>
        <a href="{% url 'agronomy:delete_event' event.pk %}">Supprimer</a>
    {% endif %}
    
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #48c422;
            text-align: center;
            align-items: normal;
        }
        button, input[type="button"], input[type="submit"] {
            background-color: #2a6105;
            color: white;
            border: none;
            padding: 5px 10px;
            text-decoration: none;
            display: inline-block;
            font-size: 10px;
            margin: 2px 2px;
            cursor: pointer;
            border-radius: 5px;
        }
    </style>
    <form method="post" action="{% url 'agronomy:vote_event' event.pk %}">
        {% csrf_token %}
        <button type="submit">Vote</button>
    </form>

    <!-- Boutons de partage vers les plateformes de médias sociaux -->
    <div class="social-share">
        <a href="https://twitter.com/intent/tweet?url={{ event.get_absolute_url }}" target="_blank">Partager sur Twitter</a>
        <a href="https://www.facebook.com/sharer/sharer.php?u={{ event.get_absolute_url }}" target="_blank">Partager sur Facebook</a>
    </div>


    <form action="{% url 'agronomy:upload_event' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Télécharger l'événement</button>
    </form>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/event_form.html
<p>
    <a href="{% url 'agronomy:article_list' %}">Articles_list</a>
</p>

{% block title %}Create Event{% endblock %}

{% block content %}
    <a href="{% url 'agronomy:event_list' %}">  </a>

    <form action="{% url 'agronomy:create_event' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        
            <input type="submit" value="Submit">
    </form>
 
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #48c422;
            text-align: center;
}
    </style>
{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/event_view.html
{% extends 'base_template.html' %}

{% block title %}{{ event.title }}{% endblock %}

{% block content %}



    <h1>{{ event.title }}</h1>
    <p><strong>Description:</strong> {{ event.description }}</p>
    <p><strong>Date de début:</strong> {{ event.start_date }}</p>
    <p><strong>Date de fin:</strong> {{ event.end_date }}</p>
    <p><strong>Lieu:</strong> {{ event.location }}</p>
    <p><strong>Organisateur:</strong> {{ event.organizer }}</p>
    <p><strong>Nombre de votes:</strong> {{ event.get_vote_count }}</p>
    <p><strong>Contact:</strong> <a href="mailto:{{ event.contact_email }}">{{ event.contact_email }}</a></p>
    {% if event.website %}
        <p><strong>Site web:</strong> <a href="{{ event.website }}">{{ event.website }}</a></p>
    {% endif %}

{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/produit_add.html
{% extends 'base_template.html' %}

{% block 'title' %}Create a new Produit{% endblock %}

{% block 'content' %}
    <form action="{% url 'agronomy:produit_add' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/produit_change.html
{% extends 'base_template.html' %}

{% block 'title' %}Edit Produit: {{ produit.title }}{% endblock %}

{% block 'content' %}
    <main>
        <h1>Edit Produits Agricoles</h1>
        <form action="{% url 'agronomy:produit_change' produit.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit">
        </form>
        <p>
            <a href="{% url 'agronomy:produit_detail' produit.id %}">Back</a>
        </p>
    </main>
{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/produit_view.html
{% extends 'base_template.html' %}

{% block 'title' %}{{ produit.title }}{% endblock %}

{% block 'content' %}
    
    <h1>{{ produit.title }}</h1>
    
    <p>Published: <em>{{ produit.pub_date }}</em></p>
    
    <p>{{ produit.content }}</p>
    
    {% if produit.image %}
    <img style="width:400px" src="{{ produit.image.url }}">
    {% endif %}

{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/upload_article.html
{% extends 'base_template.html' %}

{% block 'title' %}{{ produit.title }}{% endblock %}

{% block 'content' %}


<form action="{% url 'agronomy:upload_article' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Télécharger l'article</button>
</form>

{% endblock %}

python_project/djangoproject/agronomy/templates/agronomy/upload_event.html
{% extends 'base_template.html' %}

{% block 'title' %}{{ produit.title }}{% endblock %}

{% block 'content' %}

<form action="{% url 'agronomy:upload_event' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Télécharger l'événement</button>
</form>
{% endblock %}